// name generated by sillyname package
//var generateName = require('sillyname'); -> Old format

// import generateName from "sillyname";

// var sillyName = generateName();

// console.log(`My name is ${sillyName}.`);

// name of a random superhero


import { randomSuperhero } from "superheroes";

const name = randomSuperhero();

console.log(`I am ${name}`);




